apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: clickhouse
    spec:
      containers:
      - image: yandex/clickhouse-server:19.11
        name: clickhouse
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: sentry-clickhouse
      restartPolicy: Always
      volumes:
      - name: sentry-clickhouse
        persistentVolumeClaim:
          claimName: sentry-clickhouse
status: {}
